### ISSUE TITLE
GHIA 2 - test web_smoke

### ISSUE THREAD

**Issue by petrnymsa** [cvut/ghia#10]
Narážím s největší pravděpodobností na nedokonalou znalost jak fungují importy v Pythonu. 

Mám strukturu projektu:
├───templates
├───tests
│   ├───fixtures
│   ├─── test_web_smoke.py
├───tests_environment
│
├─── ghia.py
├─── ....

Test volam
pytest tests/test_web_smoke.py

V testu je 
```Python
def _import_app():
    import ghia
# ....
```
Dostavam chybu No module named 'ghia' 

Jak mohu snadno tuhle chybu napravit?

**Comment by hroncok** [comment]
> Test volam `pytest tests/test_web_smoke.py`

Z jakého pwd?

**Comment by hroncok** [comment]
Zkusil bych:

 * pouštět testy z rotou repozitáře
 * použít `python -m pytest tests/test_web_smoke.py` ([proč?](http://doc.pytest.org/en/latest/usage.html#calling-pytest-through-python-m-pytest))

**Comment by petrnymsa** [comment]
@hroncok 
z root directory projektu, tj tam kde se nachazi ghia.py

**Comment by petrnymsa** [comment]
python -m pytest tests/test_web_smoke.py zafungovalo.
