### ISSUE TITLE
GHIA2 – smoke_test

### ISSUE THREAD

**Issue by budikpet** [cvut/ghia#12]
Why does the test_dangerous_ping_pong test (ping without signature) end with HTTP 200 even though it the test_bad_secret test (ping with bad signature) ends with HTTP 400+?

Wouldn't it make sense for both of them to have a same code because we have no idea where they are from? Either 200 (because it's just a ping) or 400+.

**Comment by hroncok** [comment]
When secret is not specified in the config, it is not checked. The `test_dangerous_ping_pong` test uses a config without a specified secret (`config_env_nosecret`).

**Comment by budikpet** [comment]
Ok, didn't see that. Closing.
