### ISSUE TITLE
ghia - test_reset jako 1. test

### ISSUE THREAD

**Issue by Hinogary** [cvut/ghia#13]
Ahoj,
u sebe jsem udělal takovou modifikaci, že jsem dal test_reset jako první test. Tím jsem dosáhl toho, že když funguje ta funkčnost, co vyžaduje test_reset, tak není důlěžitý v jakým stavu je repozitář nazačátku a projdou testy i tak. Například přerušení testů uprostřed nerozbije další spuštění testů. Nebyl by dobrý nápad aplikovat tu změnu i tady?

**Comment by MarekSuchanek** [comment]
Ahoj,
jo to je asi dobrý nápad 😄 škoda, že už je po odevzdání úlohy... ony ty testy byly od nejjednodušších po ty složitější a pak už jsem zařadil reset nakonec. Pak to ještě přehodím pro další úkoly, kde už to ale nebude asi tak důležité vzhledem ke zveřejněnému referenčnímu řešení.

Díky!

**Comment by MarekSuchanek** [comment]
Done in https://github.com/cvut/ghia/commit/b69486b978cb25e36acd82f60df818f913bc353a
