### ISSUE TITLE
GHIA 3 - flask templates folder

### ISSUE THREAD

**Issue by petrnymsa** [cvut/ghia#16]
Pokud mam balicek naisntalovany, mam problem se spustenim FLASK aplikace.

v __init__.py mam

`__all__ = ['run', 'create_app']`
Tedy spusteni (run) cli nebo create_app (flask)

v MANIFEST.in mam include ghia/templates/*
Kdyz zkontroluji vytvoreny dist package

V adresari samotneho balicku ghia je i slozka templates
Flask aplikace vola render_template('index.html',...) (index.html je ve slozce templates

Flask aplikaci spoustim
$env:FLASK_APP='ghia:create_app'
$env:FLASK_DEBUG=1
flask run

Flask aplikace se spusti, skonci s chybou jinja2.exceptions.TemplateNotFound 

Rozumim, ze nemuze najit danou template. 
Jake je spravne reseni? 
Dekuji za tipy.

**Comment by petrnymsa** [comment]
Solved
do setup.py jsem musel pridat 
`
include_package_data=True
`

**Comment by MarekSuchanek** [comment]
Do `MANIFEST.in` patří soubory, které jsou součástí balíčku, ale neinstalují se. Proto je potřeba přidat buď `include_package_data=True` (což ale pak instaluje všechny soubory vč. licence a případně dokumentace nebo příkladů konfiguračních souborů). Ideální je použít `package_data`.

Viz https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files
