### ISSUE TITLE
test_match_text

### ISSUE THREAD

**Issue by Hinogary** [cvut/ghia#2]
test mě padá na tom, že vypisuju obráceně `+ ghia-jane` a `+ ghia-anna` (u jednoho issue #1), je to problém?

**Comment by hroncok** [comment]
> Jednotlivé issues jsou seřazeny tak jak ve výchozím nastavení přijdou z GitHub API. Přiřazení uživatelé jsou v seznamu seřazeni **dle abecedy** s ignorováním velikosti písmen.

**Comment by Hinogary** [comment]
teda pro přiřazení uživatelů, aby byli seřazení správně je potřeba všechny smazat a pak je zas přiřadit seřazené podle abecedy?

**Comment by hroncok** [comment]
Ne. Stačí je podle abecedy vypsat.
