### ISSUE TITLE
Nekonzistentní názvy fallback klíčů

### ISSUE THREAD

**Issue by m-sche** [cvut/ghia#3]
V ukázce v readme se v konfiguráku v sekci `[fallback]` používá klíč `name=`, zatímco v testech, konkrétně v konfiguráku `rules.fallback_label.cfg`, se očekává `label=`. Bylo by dobré to sjednotit nebo poukázat v popisu úkolu na to, že klíč může být libovolný.

**Comment by MarekSuchanek** [comment]
Díky, opraveno v zadáni: https://github.com/cvut/ghia/commit/8b0ff81188ca075413cc7097ecdd7f31b566efc3
