### ISSUE TITLE
Kdy se nastavuje fallback

### ISSUE THREAD

**Issue by DanHampl** [cvut/ghia#4]
- Přidávám fallback, pokud nepřiřadím žádného uživatele, ale již na issue nějaký je?
- Přidávám fallback, pokud odstraním všechny uživatele v daném běhu?
- Odebírám fallback, pokud přiřadím uživatele a fallback tag je zrovna nastaven?

**Comment by MarekSuchanek** [comment]
* Fallback se přidává pokud po zpracování issue není nikdo přiřazený (tzn. někdo byl přiřazen, ale smazal jsem ho a nebo nikdo původně nebyl přiřazen a nikoho jsem nepřiřadil)
* Fallback se neodebírá
