### ISSUE TITLE
Nastavení barvy způsobí failování testů

### ISSUE THREAD

**Issue by Kasape** [cvut/ghia#5]
Snažím se nastavit barevný výpis chyby, tzn. slovíčko ERROR dát tučně a červeně, ale když to udělám, tak neprojdu testem, konkrétně "AssertionError: assert 'ERROR: Could not list issues for repository mi-pyt-ghia/kasape' in '\x1b[31m\x1b[1mERROR\x1b[0m: Could not list issues for repository mi-pyt-ghia/kasape\n'" 

Jsou testy koncipovány, abychom jimi prošli i s barevnými výpisy, nebo je máme přidat až na konci a tím zase zneplatnit testy? Případně je nějaký způsob jak nabarvit text a přitom tam nevložit ty řídící znaky? Vypisuji řetězec click.style("ERROR", fg='red', bold=True)+f": Could not list issues for repository {reposlug}"

Díky

**Comment by hroncok** [comment]
Je třeba vypisovat pomocí `click.echo` - ta funkce zajistí mj.:

 - přepsání shell escape sekvencí na Windows API volání pomocí coloarma v případě Windows
 - odebrání shell escape sekvencí v případě, že výstup nejde na interaktivní tty (např. je přesměrován do souboru nebo jej čteme v testech)

**Comment by Kasape** [comment]
Ahá, děkuju, to funguje
