### ISSUE TITLE
Výpisy a odkazy

### ISSUE THREAD

**Issue by vaceklu6** [cvut/ghia#8]
V přiložených ukázkových výpisech (obrázky), pokud se nic neprovádí nebo se vypisuje Fallback, je v http odkazu místo "issue" "pull". V přiložených testech je přesto issue.

Například: 
`-> hroncok/playground#1(https://github.com/hroncok/playground/pull/5)`

v testech se ale podle všeho očekává
`-> hroncok/playground#1(https://github.com/hroncok/playground/issue/5)`

Je to dost zmatečné a zavádějící. Budu tedy počítat, že se použije hodnota z každého issue položka url.

**Comment by MarekSuchanek** [comment]
Nechápu moc co je špatně, pull requesty mají odkaz na s `pull` a "jen" issue na `issue`. Pull request GitHub API považuje za speciální typ issue viz https://developer.github.com/v3/issues/#list-issues

> GitHub's REST API v3 considers every pull request an issue, but not every issue is a pull request.

Správné řešení je použít správně URL které přijde pro issue (které může být případně pull requestem) z API. Je potřeba to v zadání blíže specifikovat?

**Comment by vaceklu6** [comment]
Pull request poznám díky tomu že tam má sekci pull_request? Viz výsek z jsonu u odkazu:

`    "pull_request": {
      "url": "https://api.github.com/repos/octocat/Hello-World/pulls/1347",
      "html_url": "https://github.com/octocat/Hello-World/pull/1347",
      "diff_url": "https://github.com/octocat/Hello-World/pull/1347.diff",
      "patch_url": "https://github.com/octocat/Hello-World/pull/1347.patch"
    },`

Nebo jakým způsobem mám poznat, že se jedná o pull request?

**Comment by petrnymsa** [comment]
V zadání není nijak řečeno, že máme rozlišovat issue a pull request. Má se použít jednoduše url, která je svázaná s daným issue (pull requestem)

**Comment by hroncok** [comment]
Není třeba nic poznávat, stačí vypsat `issue["html_url"]`

**Comment by vaceklu6** [comment]
Nyní mi to je jasné a issue se za mě může zavřít. Děkuji za vysvětlení.

**Comment by hroncok** [comment]
> Nyní mi to je jasné

Když dostanu z API odpověď o issue, obsahuje tato odpověď „lidský odkaz“, který je třeba zobrazit. Například když dostanu tuto response:

https://developer.github.com/v3/issues/#response

```pycon
>>> for issue in r.json():
...     print(issue['html_url'])
... 
https://github.com/octocat/Hello-World/issues/1347
```

Tento lidský odkaz už je správně, tedy obsahuje pull nebo issue podle toho, zda je to pull request nebo issue.

Real life example:

```pycon
>>> r = session.get('https://api.github.com/repos/cvut/MI-PYT/issues')
>>> for issue in r.json():
...     print(issue['html_url'])
... 
https://github.com/cvut/MI-PYT/issues/152
https://github.com/cvut/MI-PYT/issues/150
https://github.com/cvut/MI-PYT/pull/148
https://github.com/cvut/MI-PYT/issues/135
https://github.com/cvut/MI-PYT/issues/119
https://github.com/cvut/MI-PYT/issues/79
https://github.com/cvut/MI-PYT/issues/76
https://github.com/cvut/MI-PYT/issues/65
https://github.com/cvut/MI-PYT/issues/63
https://github.com/cvut/MI-PYT/issues/57
```

Nikde jsem nic nerozhodoval, jen vypisuju jednu a tu samou věc a ta vypadá pro #148 jinak.
