### ISSUE TITLE
GHIA 2 - extra repozitář username-web

### ISSUE THREAD

**Issue by petrnymsa** [cvut/ghia#9]
V zádání se píše 
`Nasazenou aplikaci nastavte tak, abychom mohli chování vyzkoušet vytvářením issues ve Vašem repozitáři mi-pyt-ghia/<username>-web`

Máme si tedy v rámci mi-pyt-ghia skupiny založit ještě jeden extra repozitář se suffixem "web"? Nebo postačí použít repo i s vytvořenými issues, které máme z předchozí úlohy?

**Comment by hroncok** [comment]
> Máme si tedy v rámci mi-pyt-ghia skupiny založit ještě jeden extra repozitář se suffixem "web"? 

Ano prosím.

**Comment by petrnymsa** [comment]
Diky. Zaviram.
